-- 여기는 관리자화면입니다.

CREATE TABLESPACE CBTts DATAFILE 'E:/bizwork/oradata/CBTts' SIZE 100M AUTOEXTEND ON NEXT 100k;

CREATE USER userCBT IDENTIFIED BY 1234 DEFAULT TABLESPACE CBTts;

GRANT dba to userCBT;